config/routes.rb
ProjManRails::Application.routes.draw do
  
  resources :statuses
  resources :priorities
  resources :admin
  resources :projects do
    resources :tasks
  end
  resources :groups do
  	resources :notes
  end
  
  #custom routes
  match 'projects/delete/:id' => 'projects#delete'
  match 'projects/:id/my_tasks' => 'projects#my_tasks'
  
  #match 'groups/join_group/:id' => 'groups#join_group'
  #resources :tasks

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name, :user_ids
  has_and_belongs_to_many :users
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :body, :group_id, :name
end

app/models/priority.rb
class Priority < ActiveRecord::Base
  attr_accessible :name
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks, :dependent => :destroy
  attr_accessible :name, :body, :due_date, :due_date_date, :due_date_time
  
   # add the accessors for the two fields
  attr_accessor :due_date_date, :due_date_time

  # add some callbacks
  after_initialize :get_datetimes # convert db format to accessors
  before_validation :set_datetimes # convert accessors back to db format

  def get_datetimes
    self.due_date ||= Time.now  # if the published_at time is not set, set it to now

    self.due_date_date ||= self.due_date.to_date.to_s(:db) # extract the date is yyyy-mm-dd format
    self.due_date_time ||= "#{'%02d' % self.due_date.hour}:#{'%02d' % self.due_date.min}" # extract the time
  end

  def set_datetimes
    self.due_date = "#{self.due_date_date} #{self.due_date_time}:00" # convert the two fields back to db
  end 
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :name
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
	belongs_to :project
	belongs_to :priority
	belongs_to :status
  attr_accessible :browser_version, :due_date, :due_date_time, :due_date_date, :name, :notes, :priority_id, :project_id, :status_id, :user_id
  
  # add the accessors for the two fields
  attr_accessor :due_date_date, :due_date_time

  # add some callbacks
  after_initialize :get_datetimes # convert db format to accessors
  before_validation :set_datetimes # convert accessors back to db format

  def get_datetimes
    self.due_date ||= Time.now  # if the published_at time is not set, set it to now

    self.due_date_date ||= self.due_date.to_date.to_s(:db) # extract the date is yyyy-mm-dd format
    self.due_date_time ||= "#{'%02d' % self.due_date.hour}:#{'%02d' % self.due_date.min}" # extract the time
  end

  def set_datetimes
    self.due_date = "#{self.due_date_date} #{self.due_date_time}:00" # convert the two fields back to db
  end  
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tasks, :through => :user_task
	has_and_belongs_to_many :groups
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :group_ids
  
end

app/models/user_projects.rb
class UserProjects < ActiveRecord::Base
  attr_accessible :project_id, :user_id
end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
  attr_accessible :task_id, :user_id
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	
	def index
	
	end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @projects = Project.all
    @groups = Group.all
    @tasks = Task.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	

  # GET /projects
  # GET /projects.json
  def index
  	
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end
  
  def my_tasks
    @project = Project.find(params[:id])
    @tasks = Task.where(:project_id => params[:id], :user_id => current_user)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  	
    @project = Project.find(params[:id])
    @tasks = Task.where(:project_id => params[:id], :status_id => 9 ).limit(5)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def delete
  	  @project = Project.find(params[:id])
  	  @tasks = Task.where(:project_id => params[:id], :status_id => 1 )
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def nice_date_form(the_date)
			if !the_date.nil? 
				 I18n.l the_date, :format => :short
			end
	 end
	 
	 def sortable(column, title = nil)
    title ||= column.titleize
    direction = (column == params[:sort] && params[:direction] == "asc") ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/projects/_form.html.erb
<div class="offset3">
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.label :due_date %>
    <%= f.text_field :due_date_date, :class => 'datepicker', :size => 10, :maxlength => 10 %> <%= f.text_field :due_date_time, :size => 5, :maxlength => 5 %>
    <%= f.input :body %>
  </div>
</div>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-success' %>
  </div>
<% end %>
<script type="text/javascript">
	jQuery(function() {
		jQuery('.datepicker').datepicker({dateFormat: 'yy-mm-dd'});
	});
</script>

app/views/projects/delete.html.erb
<h2>Are you sure you want to delete the project <%= @project.name %>?</h2>
<p>This will also delete all tasks related to the project <%= @project.name %> which are listed below. <strong>This cannot be undone!</strong></p>
<div class="form-actions">
	<%= link_to 'Yes I am sure', @project, :class => 'btn btn-danger', :method => 'delete', :data => {:confirm => 'One final check. Are you sure you want to delete this project?'} %>
	<%= link_to 'No, get me out of here', project_path, :class => 'btn btn-info' %>
</div>
<table class="table table-striped table-bordered">
  <tr>
    <th>Name</th>
    <th>Status</th>
  </tr>
<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.status.name %></td>
  </tr>
<% end %>
</table>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @project, :class => 'btn' %> | 
<%= link_to 'Delete', {'action' => 'delete', :id => @project.id} %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Due date</th>
    <th>Actions</th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.due_date.to_date %></td>
    <td><%= link_to 'View', project, :class => 'btn btn-primary' %>
		<%= link_to 'Edit', edit_project_path(project), :class => 'btn' %>
		<%= link_to 'Delete', {'action' => 'delete', :id => project.id}, :class => 'btn btn-danger' %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path, :class => 'btn btn-success' %>

app/views/projects/my_tasks.html.erb
<h1>Listing <%= current_user.name %>'s tasks</h1>
<div class="form-actions">
	<%= link_to raw('<i class="icon-arrow-left"></i>&nbsp;Back'), project_path(@project), :class => 'btn' %>
	<%= link_to 'New Task', new_project_task_path(@project), :class => 'btn btn-primary' %>
	<%= link_to 'All Tasks', project_tasks_url(@project), :class => 'btn' %>
</div>
<table class="table table-striped table-bordered">
  <tr>
    <th><%= link_to 'Name', :sort => "name" %>&nbsp;<i class="icon-chevron-down"></i></th>
    <th><%= link_to 'Status', :sort => 'status_id' %>&nbsp;<i class="icon-chevron-down"></i></th>
    <th>Assigned to</th>
    <th>Due date</th>
    <th>Notes</th>
    <th><%= link_to 'Priority', :sort => 'priority_id' %>&nbsp;<i class="icon-chevron-down"></i></th>
    <th>Browser version</th>
    <th>Actions</th>
  </tr>
<% @tasks.each do |task| %>
  <tr>
    <td><%= link_to task.name, project_task_path(@project, task) %></td>
    <td><%= task.status.name %></td>
    <td><%= task.user.name %></td>
    <td><%= task.due_date.to_date %></td>
    <td><%= task.notes %></td>
    <td><%= task.priority.name %></td>
    <td><%= task.browser_version %></td>
    <td><%= link_to 'Show', project_task_path(@project, task) %> | 
		<%= link_to 'Edit', edit_project_task_path(@project, task) %>
    <%= 
    	#link_to 'Destroy', project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' } 
    %></td>
  </tr>
<% end %>
</table>

<br />

<div class="form-actions">
	<%= link_to raw('<i class="icon-arrow-left"></i>&nbsp;Back'), project_path(@project), :class => 'btn' %>
	<%= link_to 'New Task', new_project_task_path(@project), :class => 'btn btn-primary' %>
	<%= link_to 'All Tasks', project_tasks_url(@project), :class => 'btn' %>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h2><%= @project.name %></h2>
<h4>Deadline: <%= @project.due_date.to_formatted_s(:short)  %></h4>
<p><%= @project.body %></p>

<%= link_to 'Edit', edit_project_path(@project), :class => 'btn' %>
<%= #link_to 'Back', projects_path, :class => 'btn' 
%>

<div class="project_tasks">
<hr />
	<h3>Recent Open Tasks</h3>
	<br />
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th width="25%">Name</th>
				<th width="10%">Status</th>
				<th width="15%">Priority</th>
				<th width="25%">Due date</th>
				<th width="25%">Assigned to</th>
			</tr>
		</thead>
		<tbody>
		<% @tasks.each do |t| %>
			<tr>
				<td><%= link_to t.name, project_task_path(@project, t)  %></td>
				<td><%= t.status.name %></td>
				<td><%= t.priority.name %></td>
				<td><%= t.due_date.to_date %></td>
				<td><%= t.user.name %></td>
			</tr>
		<% end %>
		</tbody>
	</table>
	<div class="form-actions">
		<%= link_to 'All Tasks', project_tasks_url(@project), :class => 'btn btn-primary btn-large' %>
		<%= link_to 'Add Task', new_project_task_path(@project), :class => 'btn btn-success btn-large' %>
		<%= link_to 'My Tasks', {:action => 'my_tasks'}, :class => 'btn btn-large' %>
	</div>
</div>